import { B2BItem, Job } from '@/types/types';

export const MOCK_B2B_ITEMS: B2BItem[] = [
  {
    id: '1',
    type: 'WISH',
    title: 'Seeking Organic Ginger Suppliers',
    description: 'We are a processing unit in Biratnagar looking for bulk suppliers of organic ginger from eastern districts.',
    category: 'Agriculture',
    location: 'Biratnagar, Koshi',
    postedBy: 'Eastern Spices Pvt Ltd',
    date: '2024-05-10',
    tags: ['Raw Material', 'Organic', 'Supply Chain'],
    isService: false,
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    type: 'OFFER',
    title: 'Custom ERP Software Development',
    description: 'Complete enterprise resource planning solutions tailored for manufacturing units in Nepal.',
    category: 'Technology',
    location: 'Itahari, Koshi',
    postedBy: 'Koshi Tech Solutions',
    date: '2024-05-12',
    tags: ['Software', 'Digital Transformation'],
    isService: true,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    type: 'WISH',
    title: 'Investment Partner for Boutique Hotel',
    description: 'Seeking equity partners for a new boutique hotel project in Dharan focused on cultural tourism.',
    category: 'Tourism',
    location: 'Dharan, Koshi',
    postedBy: 'Vista Hospitality',
    date: '2024-05-14',
    tags: ['Investment', 'Partnership'],
    isService: true,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    type: 'OFFER',
    title: 'High-Grade Dhaka Fabric Wholesale',
    description: 'Premium quality handmade Dhaka fabric available for bulk purchase for garment manufacturers.',
    category: 'Textiles',
    location: 'Tehrathum, Koshi',
    postedBy: 'Himalayan Weavers',
    date: '2024-05-15',
    tags: ['Textile', 'Wholesale', 'Export Quality'],
    isService: false,
    imageUrl: 'https://images.unsplash.com/photo-1520216127113-d09f7a4a9c1e?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    type: 'WISH',
    title: 'Cold Storage Logistics Partner',
    description: 'Looking for a reliable logistics partner with cold chain capabilities for transporting dairy products.',
    category: 'Agriculture',
    location: 'Birtamod, Koshi',
    postedBy: 'Kanchenjunga Dairy',
    date: '2024-05-16',
    tags: ['Logistics', 'Cold Chain'],
    isService: true,
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=800',
  },
];
